package com.voicecontrol.app.skills

/**
 * A concrete, ready-to-run plan — either instantiated from a saved Skill
 * (parameters bound) or freshly generated by the AI for a novel request.
 */
data class ExecutionPlan(
    val goal: String,
    val skillId: String?,              // null => not tied to a saved skill (candidate for saving after success)
    val steps: List<PlanStep>,
    val boundParams: Map<String, String> = emptyMap()
)

data class PlanStep(
    val index: Int,
    val action: String,                // reuses ActionExecutor's vocabulary: click, type, open_app, swipe, tap_xy, back, home, wait, done...
    val target: TargetDescriptor?,      // null for actions that don't need a target (open_app, back, home, wait)
    val inputText: String? = null,      // may contain "{param}" placeholders, resolved at bind-time
    val verification: VerificationRule,
    val optional: Boolean = false       // e.g. "dismiss permission popup if present" — skip silently if target not found
)

/**
 * How to find a node on the LIVE screen at execution time.
 * Never a raw node_id — those only survive one UI-tree snapshot.
 * Resolution order recommended in PlanExecutor: byText -> byDesc -> byType+role -> fallbackXY (last resort).
 */
data class TargetDescriptor(
    val byText: String? = null,
    val byDesc: String? = null,
    val byType: String? = null,        // "B","E","IB","TV","IV" — matches UiTreeExtractor's T field
    val fallbackXY: Pair<Int, Int>? = null
)

data class VerificationRule(
    val type: VerifyType,
    val value: String? = null          // meaning depends on type, see VerifyType docs below
)

enum class VerifyType {
    TEXT_APPEARS,       // value = text that must be present in tree after the step
    TEXT_DISAPPEARS,    // value = text that must be absent after the step (e.g. EditText cleared after send)
    SCREEN_CHANGED,     // no value needed — stabilized-tree hash must differ from pre-action hash
    APP_FOREGROUND,     // value = expected package/app name
    NODE_GONE           // value = descriptor key that should no longer resolve (e.g. a dismissed dialog)
}

sealed class ExecutionResult {
    object Success : ExecutionResult()
    data class Failed(val reason: String, val lastCompletedStep: Int) : ExecutionResult()
    data class NeedsUserInput(val question: String) : ExecutionResult()
}
